// ASYNC REQUEST TYPES

// - USER:
export const AUTHORIZE_USER_REQUEST = 'USER/AUTHORIZE_USER_REQUEST';
export const LOGOUT_USER_REQUEST = 'USER/LOGOUT_USER_REQUEST';

// - COMMENTS:
export const ADD_COMMENT_REQUEST = 'COMMENT/ADD_COMMENT_REQUEST';
export const CHANGE_COMMENT_REQUEST = 'COMMENT/CHANGE_COMMENT_REQUEST';
export const REMOVE_COMMENT_REQUEST = 'COMMENT/REMOVE_COMMENT_REQUEST';
export const REQUEST_COMMENTS = 'COMMENT/REQUEST_COMMENTS';

// - PROJECTS:
export const ADD_PROJECT_REQUEST = 'PROJECT/ADD_PROJECT_REQUEST';
export const CHANGE_PROJECT_REQUEST = 'PROJECT/CHANGE_PROJECT_REQUEST';
export const REMOVE_PROJECT_REQUEST = 'PROJECT/REMOVE_PROJECT_REQUEST';
export const REQUEST_PROJECTS = 'PROJECT/REQUEST_PROJECTS';
export const REQUEST_PROJECT = 'PROJECT/REQUEST_PROJECT';

// - TASKS:
export const ADD_TASK_REQUEST = 'TASK/ADD_TASK_REQUEST';
export const CHANGE_TASK_REQUEST = 'TASK/CHANGE_TASK_REQUEST';
export const REMOVE_TASK_REQUEST = 'TASK/REMOVE_TASK_REQUEST';
export const REQUEST_TASKS = 'TASK/REQUEST_TASKS';
export const REQUEST_TASK = 'TASK/REQUEST_TASK';

// WORK WITH STATE
// - USER:
export const AUTHORIZE_USER = 'USER/AUTHORIZE_USER';
export const LOGOUT_USER = 'USER/LOGOUT_USER';

// - COMMENTS:
export const ADD_COMMENT = 'COMMENT/ADD_COMMENT';
export const SET_COMMENT = 'COMMENT/SET_COMMENT';
export const REMOVE_COMMENT = 'COMMENT/REMOVE_COMMENT';
export const FETCH_COMMENTS = 'COMMENT/FETCH_COMMENTS';

// - PROJECTS:
export const ADD_PROJECT = 'PROJECT/ADD_PROJECT';
export const SET_PROJECT = 'PROJECT/SET_PROJECT';
export const REMOVE_PROJECT = 'PROJECT/REMOVE_PROJECT';
export const FETCH_PROJECTS = 'PROJECT/FETCH_PROJECTS';

// - TASKS:
export const ADD_TASK = 'TASK/ADD_TASK';
export const SET_TASK = 'TASK/SET_TASK';
export const REMOVE_TASK = 'TASK/REMOVE_TASK';
export const FETCH_TASKS = 'TASK/FETCH_TASKS';

// - FILTER
export const CHANGE_TASK_FILTER = 'TASK/CHANGE_TASK_FILTER';

// - MODAL
export const SHOW_MODAL = 'APP/SHOW_MODAL';
export const HIDE_MODAL = 'APP/HIDE_MODAL';

// APP STATES
// - LOADER
export const SHOW_LOADER = 'APP/SHOW_LOADER';
export const HIDE_LOADER = 'APP/HIDE_LOADER';

// - EDIT_FORM
export const SHOW_EDIT_FORM = 'APP/SHOW_EDIT_FORM';
export const HIDE_EDIT_FORM = 'APP/HIDE_EDIT_FORM';

// - ALLERTS
export const SHOW_ALERT = 'APP/SHOW_ALERT';
export const HIDE_ALERT = 'APP/HIDE_ALERT';
